version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:11
    ports:
      - 5432:5432
    volumes:
      - postgres:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=barista
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres: {}
