# Generated by Django 3.1.2 on 2020-10-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barista', '0005_auto_20201028_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates that this user has verified their email address and set a password.', verbose_name='verified'),
        ),
    ]
