# Generated by Django 3.1.2 on 2020-10-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barista', '0006_auto_20201028_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Designates that this user is subscribed to email newsletters.', verbose_name='subscribed'),
        ),
    ]
